### ISSUE TITLE
1.18.2

### ISSUE THREAD

**Issue by UsainSrht** [TheLimeGlass/Skacket#67]
Anvil GUIs not working in 1.18.2

```
[09:56:05 WARN]: [Skript] Task #9923 for Skript v2.6.1 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class net.wesjd.anvilgui.AnvilGUI
        at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:491) ~[Skacket-1.0.8.jar:?]
        at me.limeglass.skacket.elements.sections.SecOpenAnvil.walk(SecOpenAnvil.java:116) ~[Skacket-1.0.8.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88) ~[Skript.jar:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[Skript.jar:?]
        at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:85) ~[Skript.jar:?]
        at ch.njol.skript.lang.function.Function.execute(Function.java:129) ~[Skript.jar:?]
        at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:288) ~[Skript.jar:?]
        at ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52) ~[Skript.jar:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:51) ~[Skript.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60) ~[Skript.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88) ~[Skript.jar:?]
        at ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:283) ~[Skript.jar:?]
        at ch.njol.skript.command.Commands$3$1.call(Commands.java:217) ~[Skript.jar:?]
        at ch.njol.skript.command.Commands$3$1.call(Commands.java:214) ~[Skript.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftFuture.run(CraftFuture.java:88) ~[purpur-1.18.2.jar:git-Purpur-1576]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.2.jar:git-Purpur-1576]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1548) ~[purpur-1.18.2.jar:git-Purpur-1576]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1576]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1471) ~[purpur-1.18.2.jar:git-Purpur-1576]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1239) ~[purpur-1.18.2.jar:git-Purpur-1576]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.2.jar:git-Purpur-1576]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
