### ISSUE TITLE
1.8 Startup issue

### ISSUE THREAD

**Issue by RealRigBot** [TheLimeGlass/Skacket#32]
Hey! I get this error upon startup. I am using 1.8 but read `Runs on all Spigot versions, but depends on ProtocolLib.` I also read that it requires Skript 2.2+ (which I am using). Also, it did work on my 1.16 backend. I also understand that it says only 1.15 and 1.16 in the supported versions, but the "Runs on all spigot versions" got me confused.

```
[02:43:52] [Server thread/INFO]: [Skacket] Enabling Skacket v1.0.2
[02:43:52] [Server thread/ERROR]: Error occurred while enabling Skacket v1.0.2 (Is it up to date?)
java.lang.NoClassDefFoundError: ch/njol/skript/conditions/base/PropertyCondition$PropertyType
	at me.limeglass.skacket.elements.conditions.CondSignOpen.<clinit>(CondSignOpen.java:14) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_275]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_275]
	at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108) ~[?:?]
	at me.limeglass.skacket.Skacket.onEnable(Skacket.java:40) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:365) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:324) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:539) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:495) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:449) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:271) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:648) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.ClassNotFoundException: ch.njol.skript.conditions.base.PropertyCondition$PropertyType
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_275]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
	... 16 more
[02:43:52] [Server thread/INFO]: [Skacket] Disabling Skacket v1.0.2
```

**Comment by TheLimeGlass** [comment]
Has been fixed in recent versions of Skacket.
